using System.Text.Json;
using FaceRacerLive.Dto;

namespace FaceRacerLive.Monitor;

public class RaceMonitor : IRaceMonitor
{
    private static int _index = 0;

    public Task<SessionData> GetCurrentSession()
    {
        // TODO: Call the API to get the current session data

        _simulationArray ??= JsonSerializer.Deserialize<List<SessionData>>(SimulationJson);

        // Simulate 
        var session = _simulationArray[_index];
        _index = (_index + 1) % _simulationArray.Count;
        return Task.FromResult(session);
    }

    
    private static List<SessionData> _simulationArray;
    private static string SimulationJson =
        """
        [
        	{
        		"runnin_session_title": "Sesión #129",
        		"header_template": "normal",
        		"body_type": "normal",
        		"body_data": [
        			{
        				"position": 1,
        				"name": "David Romo",
        				"kart": "15",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "34.804",
        				"arrow": "red",
        				"best_time": "33.822",
        				"passed_time": 17347,
        				"percentage": 49.84197218710493,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 35493,
        				"consistency_lap": 1671,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 17457,
        				"line_percentage": 49.84197218710493,
        				"full_name": "David Romo",
        				"big_led_name": "David Romo",
        				"diff": "0.982"
        			},
        			{
        				"position": 2,
        				"name": "Jesus Reyna",
        				"kart": "3",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.434",
        				"arrow": "green",
        				"best_time": "35.104",
        				"passed_time": 3080,
        				"percentage": 8.227814286477534,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 37815,
        				"consistency_lap": 2711,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 34354,
        				"line_percentage": 8.227814286477534,
        				"full_name": "Jesus Reyna",
        				"big_led_name": "Jesus Reyna",
        				"diff": "2.330"
        			},
        			{
        				"position": 3,
        				"name": "Sebastián J...",
        				"kart": "8",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "35.431",
        				"arrow": "green",
        				"best_time": "35.180",
        				"passed_time": 32825,
        				"percentage": 92.64485902176061,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36715,
        				"consistency_lap": 1535,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 2606,
        				"line_percentage": 92.64485902176061,
        				"full_name": "Sebastián Jiménez",
        				"big_led_name": "Sebastián J...",
        				"diff": "0.251"
        			},
        			{
        				"position": 4,
        				"name": "Ricardo Mal...",
        				"kart": "13",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "35.734",
        				"arrow": "green",
        				"best_time": "35.734",
        				"passed_time": 33349,
        				"percentage": 93.32568422230928,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36538,
        				"consistency_lap": 804,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 2385,
        				"line_percentage": 93.32568422230928,
        				"full_name": "Ricardo Malacara",
        				"big_led_name": "Ricardo Mal...",
        				"diff": "-"
        			},
        			{
        				"position": 5,
        				"name": "Angel Rosales",
        				"kart": "19",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "37.051",
        				"arrow": "green",
        				"best_time": "37.051",
        				"passed_time": 37760,
        				"percentage": 101.91357858087503,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 38724,
        				"consistency_lap": 1673,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 0,
        				"line_percentage": 101.91357858087503,
        				"full_name": "Angel Rosales",
        				"big_led_name": "Angel Rosal...",
        				"diff": "-"
        			},
        			{
        				"position": 6,
        				"name": "Adrian Guti...",
        				"kart": "34",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "37.146",
        				"arrow": "green",
        				"best_time": "37.146",
        				"passed_time": 28491,
        				"percentage": 76.70004845743821,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39533,
        				"consistency_lap": 2387,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 8655,
        				"line_percentage": 76.70004845743821,
        				"full_name": "Adrian Gutierrez",
        				"big_led_name": "Adrian Guti...",
        				"diff": "-"
        			},
        			{
        				"position": 7,
        				"name": "Juan ramon ...",
        				"kart": "6",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "37.892",
        				"arrow": "green",
        				"best_time": "37.892",
        				"passed_time": 16661,
        				"percentage": 43.96970336746543,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39488,
        				"consistency_lap": 1596,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 21231,
        				"line_percentage": 43.96970336746543,
        				"full_name": "Juan ramon Castañeda Nuñez",
        				"big_led_name": "Juan ramon...",
        				"diff": "-"
        			},
        			{
        				"position": 8,
        				"name": "Juan Franci...",
        				"kart": "29",
        				"kart_color": "29abe1",
        				"passed": 9,
        				"total": 10,
        				"last_time": "38.461",
        				"arrow": "green",
        				"best_time": "38.461",
        				"passed_time": 7206,
        				"percentage": 18.735862302072228,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39690,
        				"consistency_lap": 1229,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 31255,
        				"line_percentage": 18.735862302072228,
        				"full_name": "Juan Francisco Simental Caro",
        				"big_led_name": "Juan Franci...",
        				"diff": "-"
        			},
        			{
        				"position": 9,
        				"name": "Javier Sainz",
        				"kart": "33",
        				"kart_color": "99242c",
        				"passed": 7,
        				"total": 10,
        				"last_time": "41.970",
        				"arrow": "red",
        				"best_time": "40.684",
        				"passed_time": 38226,
        				"percentage": 91.07934238741959,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 42335,
        				"consistency_lap": 1651,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 3744,
        				"line_percentage": 91.07934238741959,
        				"full_name": "Javier Sainz",
        				"big_led_name": "Javier Sain...",
        				"diff": "1.286"
        			},
        			{
        				"position": 10,
        				"name": "Mike Domínguez",
        				"kart": "22",
        				"kart_color": "99242c",
        				"passed": 7,
        				"total": 10,
        				"last_time": "42.947",
        				"arrow": "green",
        				"best_time": "42.947",
        				"passed_time": 38291,
        				"percentage": 89.15873052832562,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 43848,
        				"consistency_lap": 901,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 4656,
        				"line_percentage": 89.15873052832562,
        				"full_name": "Mike Domínguez",
        				"big_led_name": "Mike Domíng...",
        				"diff": "-"
        			},
        			{
        				"position": 11,
        				"name": "Luids Garcia",
        				"kart": "9",
        				"kart_color": "99242c",
        				"passed": 6,
        				"total": 10,
        				"last_time": "44.803",
        				"arrow": "red",
        				"best_time": "43.716",
        				"passed_time": 42339,
        				"percentage": 94.5003682789099,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 45441,
        				"consistency_lap": 1725,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 2464,
        				"line_percentage": 94.5003682789099,
        				"full_name": "Luids Garcia",
        				"big_led_name": "Luids Garci...",
        				"diff": "1.087"
        			},
        			{
        				"position": 12,
        				"name": "Joscelyn Al...",
        				"kart": "26",
        				"kart_color": "29abe1",
        				"passed": 5,
        				"total": 10,
        				"last_time": "51.076",
        				"arrow": "green",
        				"best_time": "51.076",
        				"passed_time": 47020,
        				"percentage": 92.05889263058971,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 54971,
        				"consistency_lap": 3895,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 4056,
        				"line_percentage": 92.05889263058971,
        				"full_name": "Joscelyn Alejandra Rodriguez Ramirez",
        				"big_led_name": "Joscelyn Al...",
        				"diff": "-"
        			}
        		],
        		"weather_data": {
        			"air_temp": "-",
        			"track_temp": "-",
        			"humidity": "-",
        			"air_pressure": "-"
        		},
        		"show_checkered_flag": false,
        		"time_left": null,
        		"footer_line": "<span>Individual - Josue Espinosa 34.657</span><span class=\"separator\">//</span><span>Doble - Juan Carlos Carrillo 42.720</span><span class=\"separator\">//</span>",
        		"session_ranking": "time",
        		"current_high_lap": 9,
        		"total_laps_for_all": 10,
        		"should_use_full_name": false,
        		"use_v3_safety_checkered_handler": false
        	},
        	{
        		"runnin_session_title": "Sesión #129",
        		"header_template": "normal",
        		"body_type": "normal",
        		"body_data": [
        			{
        				"position": 1,
        				"name": "David Romo",
        				"kart": "15",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "34.804",
        				"arrow": "red",
        				"best_time": "33.822",
        				"passed_time": 27347,
        				"percentage": 78.54,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 35493,
        				"consistency_lap": 1671,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 7000,
        				"line_percentage": 78.54,
        				"full_name": "David Romo",
        				"big_led_name": "David Romo",
        				"diff": "0.982"
        			},
        			{
        				"position": 2,
        				"name": "Jesus Reyna",
        				"kart": "3",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.434",
        				"arrow": "green",
        				"best_time": "35.104",
        				"passed_time": 13080,
        				"percentage": 34.95,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 37815,
        				"consistency_lap": 2711,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 24000,
        				"line_percentage": 34.95,
        				"full_name": "Jesus Reyna",
        				"big_led_name": "Jesus Reyna",
        				"diff": "2.330"
        			},
        			{
        				"position": 3,
        				"name": "Sebastián J...",
        				"kart": "8",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "35.800",
        				"arrow": "red",
        				"best_time": "35.180",
        				"passed_time": 6000,
        				"percentage": 16.9,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36715,
        				"consistency_lap": 1535,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 29500,
        				"line_percentage": 16.9,
        				"full_name": "Sebastián Jiménez",
        				"big_led_name": "Sebastián J...",
        				"diff": "0.620"
        			},
        			{
        				"position": 4,
        				"name": "Ricardo Mal...",
        				"kart": "13",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "35.734",
        				"arrow": "green",
        				"best_time": "35.734",
        				"passed_time": 7000,
        				"percentage": 19.6,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36538,
        				"consistency_lap": 804,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 28700,
        				"line_percentage": 19.6,
        				"full_name": "Ricardo Malacara",
        				"big_led_name": "Ricardo Mal...",
        				"diff": "-"
        			},
        			{
        				"position": 5,
        				"name": "Angel Rosales",
        				"kart": "19",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "37.051",
        				"arrow": "green",
        				"best_time": "37.051",
        				"passed_time": 3000,
        				"percentage": 8.1,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 38724,
        				"consistency_lap": 1673,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 34000,
        				"line_percentage": 8.1,
        				"full_name": "Angel Rosales",
        				"big_led_name": "Angel Rosal...",
        				"diff": "-"
        			},
        			{
        				"position": 6,
        				"name": "Adrian Guti...",
        				"kart": "34",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "37.146",
        				"arrow": "green",
        				"best_time": "37.146",
        				"passed_time": 38491,
        				"percentage": 103.7,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39533,
        				"consistency_lap": 2387,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 0,
        				"line_percentage": 103.7,
        				"full_name": "Adrian Gutierrez",
        				"big_led_name": "Adrian Guti...",
        				"diff": "-"
        			},
        			{
        				"position": 7,
        				"name": "Juan ramon ...",
        				"kart": "6",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "37.892",
        				"arrow": "green",
        				"best_time": "37.892",
        				"passed_time": 26661,
        				"percentage": 70.3,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39488,
        				"consistency_lap": 1596,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 11200,
        				"line_percentage": 70.3,
        				"full_name": "Juan ramon Castañeda Nuñez",
        				"big_led_name": "Juan ramon...",
        				"diff": "-"
        			},
        			{
        				"position": 8,
        				"name": "Juan Franci...",
        				"kart": "29",
        				"kart_color": "29abe1",
        				"passed": 9,
        				"total": 10,
        				"last_time": "38.461",
        				"arrow": "green",
        				"best_time": "38.461",
        				"passed_time": 17206,
        				"percentage": 44.7,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39690,
        				"consistency_lap": 1229,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 21000,
        				"line_percentage": 44.7,
        				"full_name": "Juan Francisco Simental Caro",
        				"big_led_name": "Juan Franci...",
        				"diff": "-"
        			},
        			{
        				"position": 9,
        				"name": "Javier Sainz",
        				"kart": "33",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "41.200",
        				"arrow": "green",
        				"best_time": "40.684",
        				"passed_time": 5000,
        				"percentage": 12.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 42335,
        				"consistency_lap": 1651,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 36000,
        				"line_percentage": 12.0,
        				"full_name": "Javier Sainz",
        				"big_led_name": "Javier Sain...",
        				"diff": "0.516"
        			},
        			{
        				"position": 10,
        				"name": "Mike Domínguez",
        				"kart": "22",
        				"kart_color": "99242c",
        				"passed": 7,
        				"total": 10,
        				"last_time": "42.947",
        				"arrow": "green",
        				"best_time": "42.947",
        				"passed_time": 9000,
        				"percentage": 21.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 43848,
        				"consistency_lap": 901,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 33000,
        				"line_percentage": 21.0,
        				"full_name": "Mike Domínguez",
        				"big_led_name": "Mike Domíng...",
        				"diff": "-"
        			},
        			{
        				"position": 11,
        				"name": "Luids Garcia",
        				"kart": "9",
        				"kart_color": "99242c",
        				"passed": 6,
        				"total": 10,
        				"last_time": "44.803",
        				"arrow": "red",
        				"best_time": "43.716",
        				"passed_time": 29339,
        				"percentage": 65.4,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 45441,
        				"consistency_lap": 1725,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 15500,
        				"line_percentage": 65.4,
        				"full_name": "Luids Garcia",
        				"big_led_name": "Luids Garci...",
        				"diff": "1.087"
        			},
        			{
        				"position": 12,
        				"name": "Joscelyn Al...",
        				"kart": "26",
        				"kart_color": "29abe1",
        				"passed": 5,
        				"total": 10,
        				"last_time": "51.076",
        				"arrow": "green",
        				"best_time": "51.076",
        				"passed_time": 7000,
        				"percentage": 13.7,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 54971,
        				"consistency_lap": 3895,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 44000,
        				"line_percentage": 13.7,
        				"full_name": "Joscelyn Alejandra Rodriguez Ramirez",
        				"big_led_name": "Joscelyn Al...",
        				"diff": "-"
        			}
        		],
        		"weather_data": {
        			"air_temp": "-",
        			"track_temp": "-",
        			"humidity": "-",
        			"air_pressure": "-"
        		},
        		"show_checkered_flag": false,
        		"time_left": null,
        		"footer_line": "<span>Individual - Josue Espinosa 34.657</span><span class=\"separator\">//</span><span>Doble - Juan Carlos Carrillo 42.720</span><span class=\"separator\">//</span>",
        		"session_ranking": "time",
        		"current_high_lap": 9,
        		"total_laps_for_all": 10,
        		"should_use_full_name": false,
        		"use_v3_safety_checkered_handler": false
        	},
        	{
        		"runnin_session_title": "Sesión #129",
        		"header_template": "normal",
        		"body_type": "normal",
        		"body_data": [
        			{
        				"position": 1,
        				"name": "David Romo",
        				"kart": "15",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "34.322",
        				"arrow": "green",
        				"best_time": "33.822",
        				"passed_time": 2000,
        				"percentage": 5.8,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 35450,
        				"consistency_lap": 1670,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 32000,
        				"line_percentage": 5.8,
        				"full_name": "David Romo",
        				"big_led_name": "David Romo",
        				"diff": "0.500"
        			},
        			{
        				"position": 2,
        				"name": "Jesus Reyna",
        				"kart": "3",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.200",
        				"arrow": "red",
        				"best_time": "35.104",
        				"passed_time": 23080,
        				"percentage": 61.7,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 37800,
        				"consistency_lap": 2710,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 14000,
        				"line_percentage": 61.7,
        				"full_name": "Jesus Reyna",
        				"big_led_name": "Jesus Reyna",
        				"diff": "2.096"
        			},
        			{
        				"position": 3,
        				"name": "Sebastián J...",
        				"kart": "8",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "35.180",
        				"arrow": "green",
        				"best_time": "35.180",
        				"passed_time": 16000,
        				"percentage": 44.9,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36700,
        				"consistency_lap": 1534,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 19500,
        				"line_percentage": 44.9,
        				"full_name": "Sebastián Jiménez",
        				"big_led_name": "Sebastián J...",
        				"diff": "-"
        			},
        			{
        				"position": 4,
        				"name": "Ricardo Mal...",
        				"kart": "13",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "35.734",
        				"arrow": "green",
        				"best_time": "35.734",
        				"passed_time": 17000,
        				"percentage": 47.6,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36538,
        				"consistency_lap": 804,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 18000,
        				"line_percentage": 47.6,
        				"full_name": "Ricardo Malacara",
        				"big_led_name": "Ricardo Mal...",
        				"diff": "-"
        			},
        			{
        				"position": 5,
        				"name": "Angel Rosales",
        				"kart": "19",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.051",
        				"arrow": "green",
        				"best_time": "37.051",
        				"passed_time": 14000,
        				"percentage": 37.8,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 38720,
        				"consistency_lap": 1673,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 23000,
        				"line_percentage": 37.8,
        				"full_name": "Angel Rosales",
        				"big_led_name": "Angel Rosal...",
        				"diff": "-"
        			},
        			{
        				"position": 6,
        				"name": "Adrian Guti...",
        				"kart": "34",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.146",
        				"arrow": "green",
        				"best_time": "37.146",
        				"passed_time": 8000,
        				"percentage": 21.5,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39533,
        				"consistency_lap": 2387,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 29000,
        				"line_percentage": 21.5,
        				"full_name": "Adrian Gutierrez",
        				"big_led_name": "Adrian Guti...",
        				"diff": "-"
        			},
        			{
        				"position": 7,
        				"name": "Juan ramon ...",
        				"kart": "6",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.892",
        				"arrow": "green",
        				"best_time": "37.892",
        				"passed_time": 36661,
        				"percentage": 96.8,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39488,
        				"consistency_lap": 1596,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 1200,
        				"line_percentage": 96.8,
        				"full_name": "Juan ramon Castañeda Nuñez",
        				"big_led_name": "Juan ramon...",
        				"diff": "-"
        			},
        			{
        				"position": 8,
        				"name": "Juan Franci...",
        				"kart": "29",
        				"kart_color": "29abe1",
        				"passed": 9,
        				"total": 10,
        				"last_time": "38.461",
        				"arrow": "green",
        				"best_time": "38.461",
        				"passed_time": 27206,
        				"percentage": 70.7,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39690,
        				"consistency_lap": 1229,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 11200,
        				"line_percentage": 70.7,
        				"full_name": "Juan Francisco Simental Caro",
        				"big_led_name": "Juan Franci...",
        				"diff": "-"
        			},
        			{
        				"position": 9,
        				"name": "Javier Sainz",
        				"kart": "33",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "40.684",
        				"arrow": "green",
        				"best_time": "40.684",
        				"passed_time": 15000,
        				"percentage": 36.9,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 42300,
        				"consistency_lap": 1651,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 25500,
        				"line_percentage": 36.9,
        				"full_name": "Javier Sainz",
        				"big_led_name": "Javier Sain...",
        				"diff": "-"
        			},
        			{
        				"position": 10,
        				"name": "Mike Domínguez",
        				"kart": "22",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "43.500",
        				"arrow": "red",
        				"best_time": "42.947",
        				"passed_time": 19000,
        				"percentage": 44.3,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 43840,
        				"consistency_lap": 901,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 24000,
        				"line_percentage": 44.3,
        				"full_name": "Mike Domínguez",
        				"big_led_name": "Mike Domíng...",
        				"diff": "0.553"
        			},
        			{
        				"position": 11,
        				"name": "Luids Garcia",
        				"kart": "9",
        				"kart_color": "99242c",
        				"passed": 6,
        				"total": 10,
        				"last_time": "44.803",
        				"arrow": "red",
        				"best_time": "43.716",
        				"passed_time": 39339,
        				"percentage": 88.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 45441,
        				"consistency_lap": 1725,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 5400,
        				"line_percentage": 88.0,
        				"full_name": "Luids Garcia",
        				"big_led_name": "Luids Garci...",
        				"diff": "1.087"
        			},
        			{
        				"position": 12,
        				"name": "Joscelyn Al...",
        				"kart": "26",
        				"kart_color": "29abe1",
        				"passed": 5,
        				"total": 10,
        				"last_time": "51.076",
        				"arrow": "green",
        				"best_time": "51.076",
        				"passed_time": 17000,
        				"percentage": 33.3,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 54971,
        				"consistency_lap": 3895,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 34000,
        				"line_percentage": 33.3,
        				"full_name": "Joscelyn Alejandra Rodriguez Ramirez",
        				"big_led_name": "Joscelyn Al...",
        				"diff": "-"
        			}
        		],
        		"weather_data": {
        			"air_temp": "-",
        			"track_temp": "-",
        			"humidity": "-",
        			"air_pressure": "-"
        		},
        		"show_checkered_flag": false,
        		"time_left": null,
        		"footer_line": "<span>Individual - Josue Espinosa 34.657</span><span class=\"separator\">//</span><span>Doble - Juan Carlos Carrillo 42.720</span><span class=\"separator\">//</span>",
        		"session_ranking": "time",
        		"current_high_lap": 10,
        		"total_laps_for_all": 10,
        		"should_use_full_name": false,
        		"use_v3_safety_checkered_handler": false
        	},
        	{
        		"runnin_session_title": "Sesión #129",
        		"header_template": "normal",
        		"body_type": "normal",
        		"body_data": [
        			{
        				"position": 1,
        				"name": "David Romo",
        				"kart": "15",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "33.822",
        				"arrow": "green",
        				"best_time": "33.822",
        				"passed_time": 14000,
        				"percentage": 41.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 35400,
        				"consistency_lap": 1665,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 20000,
        				"line_percentage": 41.0,
        				"full_name": "David Romo",
        				"big_led_name": "David Romo",
        				"diff": "-"
        			},
        			{
        				"position": 2,
        				"name": "Jesus Reyna",
        				"kart": "3",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "35.104",
        				"arrow": "green",
        				"best_time": "35.104",
        				"passed_time": 6000,
        				"percentage": 17.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 37750,
        				"consistency_lap": 2705,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 29000,
        				"line_percentage": 17.0,
        				"full_name": "Jesus Reyna",
        				"big_led_name": "Jesus Reyna",
        				"diff": "-"
        			},
        			{
        				"position": 3,
        				"name": "Sebastián J...",
        				"kart": "8",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "35.950",
        				"arrow": "red",
        				"best_time": "35.180",
        				"passed_time": 12000,
        				"percentage": 33.2,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36720,
        				"consistency_lap": 1536,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 24000,
        				"line_percentage": 33.2,
        				"full_name": "Sebastián Jiménez",
        				"big_led_name": "Sebastián J...",
        				"diff": "0.770"
        			},
        			{
        				"position": 4,
        				"name": "Ricardo Mal...",
        				"kart": "13",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "35.734",
        				"arrow": "green",
        				"best_time": "35.734",
        				"passed_time": 11000,
        				"percentage": 30.8,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36530,
        				"consistency_lap": 804,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 25000,
        				"line_percentage": 30.8,
        				"full_name": "Ricardo Malacara",
        				"big_led_name": "Ricardo Mal...",
        				"diff": "-"
        			},
        			{
        				"position": 5,
        				"name": "Angel Rosales",
        				"kart": "19",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.051",
        				"arrow": "green",
        				"best_time": "37.051",
        				"passed_time": 24000,
        				"percentage": 64.8,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 38710,
        				"consistency_lap": 1673,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 14000,
        				"line_percentage": 64.8,
        				"full_name": "Angel Rosales",
        				"big_led_name": "Angel Rosal...",
        				"diff": "-"
        			},
        			{
        				"position": 6,
        				"name": "Adrian Guti...",
        				"kart": "34",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "37.146",
        				"arrow": "green",
        				"best_time": "37.146",
        				"passed_time": 18000,
        				"percentage": 48.4,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39520,
        				"consistency_lap": 2387,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 19000,
        				"line_percentage": 48.4,
        				"full_name": "Adrian Gutierrez",
        				"big_led_name": "Adrian Guti...",
        				"diff": "-"
        			},
        			{
        				"position": 7,
        				"name": "Juan ramon ...",
        				"kart": "6",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "37.892",
        				"arrow": "green",
        				"best_time": "37.892",
        				"passed_time": 3000,
        				"percentage": 8.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39470,
        				"consistency_lap": 1596,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 34000,
        				"line_percentage": 8.0,
        				"full_name": "Juan ramon Castañeda Nuñez",
        				"big_led_name": "Juan ramon...",
        				"diff": "-"
        			},
        			{
        				"position": 8,
        				"name": "Juan Franci...",
        				"kart": "29",
        				"kart_color": "29abe1",
        				"passed": 10,
        				"total": 10,
        				"last_time": "38.461",
        				"arrow": "green",
        				"best_time": "38.461",
        				"passed_time": 4000,
        				"percentage": 10.4,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39680,
        				"consistency_lap": 1229,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 33000,
        				"line_percentage": 10.4,
        				"full_name": "Juan Francisco Simental Caro",
        				"big_led_name": "Juan Franci...",
        				"diff": "-"
        			},
        			{
        				"position": 9,
        				"name": "Javier Sainz",
        				"kart": "33",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "40.684",
        				"arrow": "green",
        				"best_time": "40.684",
        				"passed_time": 29000,
        				"percentage": 70.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 42290,
        				"consistency_lap": 1651,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 12500,
        				"line_percentage": 70.0,
        				"full_name": "Javier Sainz",
        				"big_led_name": "Javier Sain...",
        				"diff": "-"
        			},
        			{
        				"position": 10,
        				"name": "Mike Domínguez",
        				"kart": "22",
        				"kart_color": "99242c",
        				"passed": 8,
        				"total": 10,
        				"last_time": "42.947",
        				"arrow": "green",
        				"best_time": "42.947",
        				"passed_time": 33000,
        				"percentage": 78.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 43830,
        				"consistency_lap": 901,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 9500,
        				"line_percentage": 78.0,
        				"full_name": "Mike Domínguez",
        				"big_led_name": "Mike Domíng...",
        				"diff": "-"
        			},
        			{
        				"position": 11,
        				"name": "Luids Garcia",
        				"kart": "9",
        				"kart_color": "99242c",
        				"passed": 7,
        				"total": 10,
        				"last_time": "44.150",
        				"arrow": "green",
        				"best_time": "43.716",
        				"passed_time": 7000,
        				"percentage": 15.9,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 45430,
        				"consistency_lap": 1720,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 37000,
        				"line_percentage": 15.9,
        				"full_name": "Luids Garcia",
        				"big_led_name": "Luids Garci...",
        				"diff": "0.434"
        			},
        			{
        				"position": 12,
        				"name": "Joscelyn Al...",
        				"kart": "26",
        				"kart_color": "29abe1",
        				"passed": 6,
        				"total": 10,
        				"last_time": "50.800",
        				"arrow": "green",
        				"best_time": "50.800",
        				"passed_time": 8000,
        				"percentage": 15.7,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 54950,
        				"consistency_lap": 3890,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 43000,
        				"line_percentage": 15.7,
        				"full_name": "Joscelyn Alejandra Rodriguez Ramirez",
        				"big_led_name": "Joscelyn Al...",
        				"diff": "-"
        			}
        		],
        		"weather_data": {
        			"air_temp": "-",
        			"track_temp": "-",
        			"humidity": "-",
        			"air_pressure": "-"
        		},
        		"show_checkered_flag": false,
        		"time_left": null,
        		"footer_line": "<span>Individual - Josue Espinosa 34.657</span><span class=\"separator\">//</span><span>Doble - Juan Carlos Carrillo 42.720</span><span class=\"separator\">//</span>",
        		"session_ranking": "time",
        		"current_high_lap": 10,
        		"total_laps_for_all": 10,
        		"should_use_full_name": false,
        		"use_v3_safety_checkered_handler": false
        	},
        	{
        		"runnin_session_title": "Sesión #129",
        		"header_template": "normal",
        		"body_type": "normal",
        		"body_data": [
        			{
        				"position": 1,
        				"name": "David Romo",
        				"kart": "15",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "33.950",
        				"arrow": "red",
        				"best_time": "33.822",
        				"passed_time": 32000,
        				"percentage": 93.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 35390,
        				"consistency_lap": 1660,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": true,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 2500,
        				"line_percentage": 93.0,
        				"full_name": "David Romo",
        				"big_led_name": "David Romo",
        				"diff": "0.128"
        			},
        			{
        				"position": 2,
        				"name": "Jesus Reyna",
        				"kart": "3",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "35.400",
        				"arrow": "red",
        				"best_time": "35.104",
        				"passed_time": 30000,
        				"percentage": 84.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 37740,
        				"consistency_lap": 2700,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": true,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 6000,
        				"line_percentage": 84.0,
        				"full_name": "Jesus Reyna",
        				"big_led_name": "Jesus Reyna",
        				"diff": "0.296"
        			},
        			{
        				"position": 3,
        				"name": "Sebastián J...",
        				"kart": "8",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "35.180",
        				"arrow": "green",
        				"best_time": "35.180",
        				"passed_time": 31000,
        				"percentage": 87.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36710,
        				"consistency_lap": 1535,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": true,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 5000,
        				"line_percentage": 87.0,
        				"full_name": "Sebastián Jiménez",
        				"big_led_name": "Sebastián J...",
        				"diff": "-"
        			},
        			{
        				"position": 4,
        				"name": "Ricardo Mal...",
        				"kart": "13",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "35.734",
        				"arrow": "green",
        				"best_time": "35.734",
        				"passed_time": 33000,
        				"percentage": 92.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 36525,
        				"consistency_lap": 804,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": true,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 2900,
        				"line_percentage": 92.0,
        				"full_name": "Ricardo Malacara",
        				"big_led_name": "Ricardo Mal...",
        				"diff": "-"
        			},
        			{
        				"position": 5,
        				"name": "Angel Rosales",
        				"kart": "19",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "37.051",
        				"arrow": "green",
        				"best_time": "37.051",
        				"passed_time": 11000,
        				"percentage": 29.7,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 38690,
        				"consistency_lap": 1670,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 26000,
        				"line_percentage": 29.7,
        				"full_name": "Angel Rosales",
        				"big_led_name": "Angel Rosal...",
        				"diff": "-"
        			},
        			{
        				"position": 6,
        				"name": "Adrian Guti...",
        				"kart": "34",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "37.146",
        				"arrow": "green",
        				"best_time": "37.146",
        				"passed_time": 9000,
        				"percentage": 24.2,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39510,
        				"consistency_lap": 2380,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 28000,
        				"line_percentage": 24.2,
        				"full_name": "Adrian Gutierrez",
        				"big_led_name": "Adrian Guti...",
        				"diff": "-"
        			},
        			{
        				"position": 7,
        				"name": "Juan ramon ...",
        				"kart": "6",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "37.892",
        				"arrow": "green",
        				"best_time": "37.892",
        				"passed_time": 24000,
        				"percentage": 63.3,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39460,
        				"consistency_lap": 1590,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": true,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 14000,
        				"line_percentage": 63.3,
        				"full_name": "Juan ramon Castañeda Nuñez",
        				"big_led_name": "Juan ramon...",
        				"diff": "-"
        			},
        			{
        				"position": 8,
        				"name": "Juan Franci...",
        				"kart": "29",
        				"kart_color": "29abe1",
        				"passed": 10,
        				"total": 10,
        				"last_time": "38.461",
        				"arrow": "green",
        				"best_time": "38.461",
        				"passed_time": 22000,
        				"percentage": 57.2,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 39670,
        				"consistency_lap": 1225,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": true,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 16500,
        				"line_percentage": 57.2,
        				"full_name": "Juan Francisco Simental Caro",
        				"big_led_name": "Juan Franci...",
        				"diff": "-"
        			},
        			{
        				"position": 9,
        				"name": "Javier Sainz",
        				"kart": "33",
        				"kart_color": "99242c",
        				"passed": 10,
        				"total": 10,
        				"last_time": "40.684",
        				"arrow": "green",
        				"best_time": "40.684",
        				"passed_time": 10000,
        				"percentage": 24.0,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 42280,
        				"consistency_lap": 1650,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": true,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 32000,
        				"line_percentage": 24.0,
        				"full_name": "Javier Sainz",
        				"big_led_name": "Javier Sain...",
        				"diff": "-"
        			},
        			{
        				"position": 10,
        				"name": "Mike Domínguez",
        				"kart": "22",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "42.947",
        				"arrow": "green",
        				"best_time": "42.947",
        				"passed_time": 43000,
        				"percentage": 101.5,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 43820,
        				"consistency_lap": 900,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 0,
        				"line_percentage": 101.5,
        				"full_name": "Mike Domínguez",
        				"big_led_name": "Mike Domíng...",
        				"diff": "-"
        			},
        			{
        				"position": 11,
        				"name": "Luids Garcia",
        				"kart": "9",
        				"kart_color": "99242c",
        				"passed": 9,
        				"total": 10,
        				"last_time": "43.716",
        				"arrow": "green",
        				"best_time": "43.716",
        				"passed_time": 26000,
        				"percentage": 59.5,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 45420,
        				"consistency_lap": 1715,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 17500,
        				"line_percentage": 59.5,
        				"full_name": "Luids Garcia",
        				"big_led_name": "Luids Garci...",
        				"diff": "-"
        			},
        			{
        				"position": 12,
        				"name": "Joscelyn Al...",
        				"kart": "26",
        				"kart_color": "29abe1",
        				"passed": 6,
        				"total": 10,
        				"last_time": "50.800",
        				"arrow": "green",
        				"best_time": "50.800",
        				"passed_time": 18000,
        				"percentage": 35.3,
        				"s1": "-",
        				"s2": "-",
        				"s3": "-",
        				"s1_status": "good",
        				"s2_status": "good",
        				"s3_status": "good",
        				"avg_lap": 54930,
        				"consistency_lap": 3880,
        				"number_of_pits": 0,
        				"checkered_flag_mode_at": null,
        				"checkered_flag": false,
        				"time_before_end_to_check_for_race_leader": 0,
        				"front_flag": null,
        				"line_guess": 33000,
        				"line_percentage": 35.3,
        				"full_name": "Joscelyn Alejandra Rodriguez Ramirez",
        				"big_led_name": "Joscelyn Al...",
        				"diff": "-"
        			}
        		],
        		"weather_data": {
        			"air_temp": "-",
        			"track_temp": "-",
        			"humidity": "-",
        			"air_pressure": "-"
        		},
        		"show_checkered_flag": true,
        		"time_left": null,
        		"footer_line": "<span>Individual - Josue Espinosa 34.657</span><span class=\"separator\">//</span><span>Doble - Juan Carlos Carrillo 42.720</span><span class=\"separator\">//</span>",
        		"session_ranking": "time",
        		"current_high_lap": 10,
        		"total_laps_for_all": 10,
        		"should_use_full_name": false,
        		"use_v3_safety_checkered_handler": false
        	},
        	{
        		"runnin_session_title": null,
        		"header_template": "normal",
        		"body_type": "normal",
        		"body_data": [],
        		"weather_data": {
        			"air_temp": "-",
        			"track_temp": "-",
        			"humidity": "-",
        			"air_pressure": "-"
        		},
        		"show_checkered_flag": false,
        		"time_left": null,
        		"footer_line": "<span>Individual - David Romo 33.432<\/span><span class=\"separator\">\/\/<\/span><span>Doble - Juan Francisco Simental Caro 38.461<\/span><span class=\"separator\">\/\/<\/span>",
        		"session_ranking": "time",
        		"current_high_lap": null,
        		"total_laps_for_all": null,
        		"should_use_full_name": false,
        		"use_v3_safety_checkered_handler": false
        	},
        	{
        		"runnin_session_title": null,
        		"header_template": "normal",
        		"body_type": "normal",
        		"body_data": [],
        		"weather_data": {
        			"air_temp": "-",
        			"track_temp": "-",
        			"humidity": "-",
        			"air_pressure": "-"
        		},
        		"show_checkered_flag": false,
        		"time_left": null,
        		"footer_line": "<span>Individual - David Romo 33.432<\/span><span class=\"separator\">\/\/<\/span><span>Doble - Juan Francisco Simental Caro 38.461<\/span><span class=\"separator\">\/\/<\/span>",
        		"session_ranking": "time",
        		"current_high_lap": null,
        		"total_laps_for_all": null,
        		"should_use_full_name": false,
        		"use_v3_safety_checkered_handler": false
        	}	
        ]
        """;
}